apiVersion: v1
kind: Service
metadata:
  name: k5smovie-infochat-svc
  labels:
    app: k5smovie-infochat-svc
spec:
  type: NodePort
  selector:
    app: k5smovie-infochat
  ports:
    - protocol : TCP
      port : 80
      targetPort : 8080
